spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: nechto
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=nechto
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: false
      client:
        config:
          telegram:
            loggerLevel: FULL

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  logging:
    level:
      org:
        springframework:
          security: debug
telegrambot:
  webHookPath: https://7a7af00cfb51.ngrok-free.app
  userName: nechto21_bot
  botToken: 8086975968:AAEWRBWduBoPDT7TUJpFlO5s_fOVvkvqSvY
server:
  port: 8080

logging:
  level:
    feign-dump: TRACE
    nechto.service.TelegramFeignClient: DEBUG
    feign: DEBUG

