package nechto.enums;

public enum BotState {
    CREATE_GAME,
    COUNT,
    ADD_USER,
    START_REGISTRATION,
    REGISTRATION,
    START,
    SHOW_RESULTS,
    SHOW_RESULTS_FOR_A_DAY,
    SHOW_RESULTS_FOR_A_MONTH,
    SHOW_RESULTS_FOR_A_QUARTER,
    CHANGE_GAME,
    MAKE_ADMIN_START,
    MAKE_ADMIN,
    MAKE_USER_START,
    MAKE_USER
}
