package nechto.enums;

public enum BotState {
    CREATE_GAME,
    COUNT,
    START_COUNT,
    ADD_USER,
    START_REGISTRATION,
    REGISTRATION,
    START,
    SHOW_RESULTS,
    START_SHOW_RESULTS_FOR_A_PERIOD,
    SHOW_RESULTS_FOR_A_PERIOD,
    START_CHANGE_GAME,
    CHANGE_GAME,
    MAKE_ADMIN_START,
    MAKE_ADMIN,
    MAKE_USER_START,
    MAKE_USER
}
