package nechto.enums;

import lombok.Getter;

@Getter
public enum Button {
    WIN_BUTTON,
    LOOSE_BUTTON,
    BURNED_BUTTON,
    WIN_NECHTO_BUTTON,
    WIN_PEOPLE_BUTTON,
    NECHTO_BUTTON,
    CONTAMINATED_BUTTON,
    LAST_CONTAMINATED_BUTTON,
    HUMAN_BUTTON,
    FLAMETHROWER_BUTTON,
    FLAMETHROWER_FOR_HUMAN_BUTTON,
    AGAINST_HUMAN_FLAMETHROWER_BUTTON,
    DANGEROUS_BUTTON,
    USEFULL_BUTTON,
    VICTIM_BUTTON,
    END_COUNT_BUTTON,
    END_GAME_BUTTON,
    COUNT_NEXT_BUTTON,
    MINUS_BUTTON,
    PLUS_BUTTON,
    MINUS_FOR_AGAINST_HUMAN_FLAMETHROWER_BUTTON,
    PLUS_FOR_AGAINST_HUMAN_FLAMETHROWER_BUTTON,
    MINUS_WITH_AGAINST_FLAMETHROWER_BUTTON,
    PLUS_WITH_AGAINST_FLAMETHROWER_BUTTON,
    VALUE_BUTTON,
    CALNAV_BUTTON,
    CALNAV_BUTTON_MONTH,
    CAL_BUTTON,
    CALNOOP_BUTTON,
    PICKED_BUTTON,
    CONFIRM_MONTH_BUTTON,
    YES_LAST_CONTAMINATED_BUTTON,
    NO_LAST_CONTAMINATED_BUTTON,
    YES_BURNED_BUTTON,
    NO_BURNED_BUTTON
}
