package nechto.enums;

import lombok.Getter;

@Getter
public enum Button {

    WIN_BUTTON("WIN_BUTTON"),
    LOOSE_BUTTON("LOOSE_BUTTON"),
    BURNED_BUTTON("BURNED_BUTTON"),
    NECHTO_BUTTON("NECHTO_BUTTON"),
    CONTAMINATED_BUTTON("CONTAMINATED_BUTTON"),
    HUMAN_BUTTON("HUMAN_BUTTON"),
    FLAMETHROWER_BUTTON("FLAMETHROWER_BUTTON"),
    ANTI_HUMAN_FLAMETHROWER_BUTTON("ANTI_HUMAN_FLAMETHROWER_BUTTON"),
    DANGEROUS_BUTTON("DANGEROUS_BUTTON"),
    USEFULL_BUTTON("USEFULL_BUTTON"),
    VICTIM_BUTTON("VICTIM_BUTTON"),
    FLAMETHROWER_BUTTON_FOR_HUMAN("FLAMETHROWER_BUTTON_FOR_HUMAN"),
    END_COUNT_BUTTON("END_COUNT_BUTTON"),
    END_GAME_BUTTON("END_GAME_BUTTON"),
    CHANGE_GAME_BUTTON("CHANGE_GAME_BUTTON"),
    CHANGE_NEXT_BUTTON("CHANGE_GAME_BUTTON"),
    COUNT_NEXT_BUTTON("COUNT_NEXT_BUTTON"),
    MINUS_BUTTON("MINUS_BUTTON"),
    PLUS_BUTTON("PLUS_BUTTON"),
    MINUS_ANTI_HUMAN_BUTTON("MINUS_ANTI_HUMAN_BUTTON"),
    PLUS_ANTI_HUMAN_BUTTON("PLUS_ANTI_HUMAN_BUTTON"),
    MINUS_ANTI_FLAMETHROWER_BUTTON("MINUS_ANTI_FLAMETHROWER_BUTTON"),
    PLUS_ANTI_FLAMETHROWER_BUTTON("PLUS_ANTI_FLAMETHROWER_BUTTON"),
    VALUE_BUTTON("VALUE_BUTTON");

    private String name;

    Button(String name) {
        this.name = name;
    }

}
