package nechto.enums;

import lombok.Getter;

@Getter
public enum Button {

    WIN_BUTTON,
    LOOSE_BUTTON,
    BURNED_BUTTON,
    WIN_NECHTO_BUTTON,
    WIN_PEOPLE_BUTTON,
    NECHTO_BUTTON,
    CONTAMINATED_BUTTON,
    LAST_CONTAMINATED_BUTTON,
    HUMAN_BUTTON,
    FLAMETHROWER_BUTTON,
    ANTI_HUMAN_FLAMETHROWER_BUTTON,
    DANGEROUS_BUTTON,
    USEFULL_BUTTON,
    VICTIM_BUTTON,
    FLAMETHROWER_BUTTON_FOR_HUMAN,
    END_COUNT_BUTTON,
    END_GAME_BUTTON,
    CHANGE_NEXT_BUTTON,
    COUNT_NEXT_BUTTON,
    MINUS_BUTTON,
    PLUS_BUTTON,
    MINUS_ANTI_HUMAN_BUTTON,
    PLUS_ANTI_HUMAN_BUTTON,
    MINUS_ANTI_FLAMETHROWER_BUTTON,
    PLUS_ANTI_FLAMETHROWER_BUTTON,
    VALUE_BUTTON,
    CALNAV_BUTTON,
    CAL_BUTTON,
    CALNOOP_BUTTON,
    CONFIRM_MONTH_BUTTON
}
